#!/bin/bash

# Prepare source for RPM build

# download langs from transifex

# tar directory
set -e

pushd ui
NODE_OPTIONS="--openssl-legacy-provider" npm install
NODE_OPTIONS="--openssl-legacy-provider" npm run build
popd

tar -C ui/dist -c -z -f nethserver-firewall-migration-cockpit.tar.gz .
