#!/bin/bash

# Prepare source for RPM build

# download langs from transifex

# tar directory
set -e

# GitHub action doesn't support NODE_OPTIONS env variable
if [ -z "$CI" ]; then
    NODE_OPTIONS="--openssl-legacy-provider"
    export NODE_OPTIONS
fi

pushd ui
npm install
npm run build
popd

tar -C ui/dist -c -z -f nethserver-firewall-migration-cockpit.tar.gz .
