#!/usr/bin/perl

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use JSON;
use esmith::ConfigDB;

my $cdb = esmith::ConfigDB->open_ro();

my %ntp;

my $enabled = $cdb->get_prop('chronyd', 'status') eq 'enabled' ? 1 : 0;
$ntp{'enabled'} = $enabled;
my @servers = split(/,/, ($cdb->get_prop('chronyd', 'NTPServer') || ''));
$ntp{'server'} = \@servers;
$ntp{'enable_server'} = ($enabled && $cdb->get_prop('chronyd', 'access') eq 'green') ? 1 : 0;

print(encode_json({'timezone' => $cdb->get_value('TimeZone'), 'ntp' => \%ntp}));
