#!/usr/bin/perl

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use JSON;
use esmith::ConfigDB;

sub role2zone {
    my $role = shift;
    if ($role eq 'green') {
        return 'lan';
    } elsif ($role eq 'red') {
        return 'wan';
    } elsif ($role eq 'hotsp') {
        return 'hotspot';
    } elsif ($role eq 'blue') {
        return 'guest';
    } elsif ($role eq 'orange') {
        return 'dmz';
    }
    return $role;
}


my $cdb = esmith::ConfigDB->open_ro();

my %config;

# Do not produce JSON output if package is not installed
$cdb->get('flashstart') || exit 0;

my @bypass = split(/,/, ($cdb->get_prop('flashstart', 'Bypass') || ''));
my @roles;
for (split(/,/, ($cdb->get_prop('flashstart', 'Roles') || ''))) {
    push(@roles, role2zone($_));
}

$config{'enabled'} = ($cdb->get_prop('flashstart', 'status') || '') eq 'enabled' ? '1' : '0';
$config{'user'} = ($cdb->get_prop('flashstart', 'Username') || '');
$config{'password'} = ($cdb->get_prop('flashstart', 'Password') || '');
$config{'bypass'} = \@bypass;
$config{'zones'} = \@roles;

print(encode_json({'config' => \%config}));
