#!/usr/bin/perl

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use JSON;
use esmith::ConfigDB;

sub slurp {
    my $file = shift;
    my $data;
    open my $fh, '<', $file or die;
    local $/ = undef;
    $data = <$fh>;
    close $fh;

    # trim
    $data =~ s/^\s+|\s+$//g;

    return $data;
}

my $rdb = esmith::ConfigDB->open_ro('routes');

my @routes;

for my $r ($rdb->get_all_by_prop('type' => 'static')) {
    my $interface;
    my $addr_file = '/sys/class/net/'.$r->prop('Device').'/address';
    if (-e $addr_file) {
        $interface = slurp($addr_file);
    }
    next if (!$interface);
    push(@routes, {
        'interface' => $interface,
        'target' => $r->key,
        'gateway' =>  $r->prop('Router'),
        'metric' =>  $r->prop('Metric') || 0,
        'description' => $r->prop('Description') || ''
    });
}

print(encode_json({'routes' => \@routes}));
