#!/usr/bin/perl

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use JSON;
use esmith::NetworksDB;
use esmith::ConfigDB;

sub slurp {
    my $file = shift;
    my $data;
    open my $fh, '<', $file or die;
    local $/ = undef;
    $data = <$fh>;
    close $fh;

    # trim
    $data =~ s/^\s+|\s+$//g;

    return $data;
}

my $cdb = esmith::ConfigDB->open_ro();
my $ndb = esmith::NetworksDB->open_ro();

my @providers;
my %general;
my %devices;

for my $i ($ndb->get_all_by_prop('type' => 'ethernet')) {
    my $addr_file = '/sys/class/net/'.$i->key.'/address';
    if (-e $addr_file) {
        $devices{$i->key} = slurp($addr_file);
    }
}

my @track_ip = split(/,/, $cdb->get_prop('firewall', 'CheckIP'));
$general{'mode'} = $cdb->get_prop('firewall', 'WanMode') || 'balanced';
$general{'track_ip'} = \@track_ip;
$general{'reliability'} = scalar(@track_ip);
$general{'interval'} = $cdb->get_prop('firewall', 'PingInterval') || '5';

for my $provider ($ndb->get_all_by_prop('type' => 'provider')) {
    my $device = $devices{$provider->prop('interface')} || next;
    push(@providers, {
        'name' => $provider->key,
        'weight' => $provider->prop('weight') || '1',
        'device' => $device
    })
}

print(encode_json({
            'providers' => \@providers,
            'general' => \%general,
        }));
