#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

OUT_DIR='/var/lib/nethserver/firewall-migration'

tmp_dir=$(mktemp -d)

mkdir -p "$tmp_dir/export"
mkdir -p $OUT_DIR
mkdir -p "$OUT_DIR/skipped"

for f in $(find /usr/share/nethserver-firewall-migration -type f -executable)
do
   name=$(basename $f)
   $f > "$tmp_dir/export/$name.json"
   cat "$tmp_dir/export/$name.json" | jq -r .skipped > "$OUT_DIR/skipped/$name.json"
done

pushd $tmp_dir >/dev/null
tar czf "$OUT_DIR/export.tar.gz" "export"
chmod 600 "$OUT_DIR/export.tar.gz"
popd >/dev/null

rm -rf $tmp_dir
